name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: " Thank you for raising the new issue! Your input is valued. Our author will soon review and assign it accordingly. Stay tuned for updates!"
        pr-message: "Thank you for your pull request (PR)! Your contribution is greatly appreciated. Our owner @mrsamirr will review it in the coming days. Stay tuned for updates!"
